### PR TITLE
Added a way to assign CA certificate path

### PR DESCRIPTION
**Pull request by sudiptpa**

### CODE REVIEW

**Comment by sudiptpa** [comment]
@rotassator I am using this package with Laravel v4.2, we are now getting error saying : 

"[curl] 60: SSL certificate problem: unable to get local issuer certificate [url] https://api.payway.com.au/rest/v1/single-use-tokens"

Now, as a hot fix i  have done changes in my server.

Downloaded CA cert from : https://curl.haxx.se/docs/caextract.html

and assigned it as:
```
        $gateway = Omnipay::create('PaywayRest_DirectDebit');

        $gateway->setApiKeyPublic($settings->apiKeyPublic);
        $gateway->setApiKeySecret($settings->apiKeySecret);
        $gateway->setMerchantId($settings->merchantId);
        $gateway->setTestMode($credential->is_test);

        $gateway->setSSLCertificatePath(app_path('certificate/cacert.pem'));
```
Could you please review and merge it.

**Comment by sudiptpa** [comment]
@rotassator I have already tested on our production and it started working, it would be great if you could tag a new release.

**Comment by sudiptpa** [comment]
Ping @rotassator I was waiting for this PR to be reviewed and merged.

**Review by rotassator — APPROVED** [review]
Looks good!

**Comment by sudiptpa** [comment]
@rotassator the 1.9.0 is not synced to packagist.org yet, do you have web hook setup for automatic syncing or releases and code updates?

**Comment by rotassator** [comment]
Ah. I'd initially set up the Packagist integration via Github services. They've been deprecated now in favour of webhooks, which I've set up now. Everything should be up to date. 

Thanks for letting me know. :)

**Pull request merged**
